### ISSUE TITLE
Error on loading the map v2.0.0.2 

### ISSUE THREAD

**Issue by luvssti** [ichim/LeafletForBlazor-NuGet#7]
Hi Sir Ichim!

How to resolve the error below?

Thanks!

Error: Microsoft.JSInterop.JSException: The requested module './esri_interops.js' does not provide an export named '_init_esri_basemap_layers'
SyntaxError: The requested module './esri_interops.js' does not provide an export named '_init_esri_basemap_layers'
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at LeafletForBlazor.CoreJsInterop.LoadMapPartialAsync(ParametersInitialization parameters, ParametersInitialization esri_api_parameters, ParametersInitialization plugins_parameters, ParametersInitialization ui_controls_parameters, ParametersInitialization images_overlay, DotNetObjectReference`1 dotNetObject)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)

**Comment by luvssti** [comment]
solved.

**Comment by kekoshade13** [comment]
Hi luvssti, how were you able to solve this?
